// <auto-generated />
using System;
using FirstCrudExample.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstCrudExample.Migrations
{
    [DbContext(typeof(LunarDbContext))]
    partial class LunarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FirstCrudExample.Models.Faculty", b =>
                {
                    b.Property<int>("FacultyId")
                        .HasColumnType("int")
                        .HasColumnName("facultyId");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("facultyName");

                    b.HasKey("FacultyId")
                        .HasName("PK__Faculty__DBBF6FB15141C888");

                    b.HasIndex(new[] { "FacultyName" }, "UQ__Faculty__53353D25C4E9674C")
                        .IsUnique();

                    b.ToTable("Faculty", (string)null);
                });

            modelBuilder.Entity("FirstCrudExample.Models.Student", b =>
                {
                    b.Property<long>("StdId")
                        .HasColumnType("bigint")
                        .HasColumnName("stdId");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int")
                        .HasColumnName("facultyId");

                    b.Property<DateOnly>("JoinDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("joinDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("StdAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("stdAddress");

                    b.Property<string>("StdName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("stdName");

                    b.HasKey("StdId")
                        .HasName("PK__Student__BA08FEBB4FA7AD26");

                    b.HasIndex("FacultyId");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("FirstCrudExample.Models.Userlist", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("LoginStatus")
                        .HasColumnType("bit")
                        .HasColumnName("loginStatus");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("phoneNumber");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("userName");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("userPassword");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int")
                        .HasColumnName("userTypeId");

                    b.HasKey("UserId")
                        .HasName("PK__USERLIST__CB9A1CFF506442B1");

                    b.HasIndex("UserTypeId");

                    b.HasIndex(new[] { "PhoneNumber" }, "UQ__USERLIST__4849DA013F2E9EF7")
                        .IsUnique();

                    b.ToTable("USERLIST", (string)null);
                });

            modelBuilder.Entity("FirstCrudExample.Models.Usertype", b =>
                {
                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("typeId");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("typeName");

                    b.HasKey("TypeId")
                        .HasName("PK__USERNAME__F04DF13AE90FA02B");

                    b.HasIndex(new[] { "TypeName" }, "UQ__USERNAME__A20CDB58027F8CA3")
                        .IsUnique();

                    b.ToTable("USERTYPE", (string)null);
                });

            modelBuilder.Entity("FirstCrudExample.Models.Student", b =>
                {
                    b.HasOne("FirstCrudExample.Models.Faculty", "Faculty")
                        .WithMany("Students")
                        .HasForeignKey("FacultyId")
                        .IsRequired()
                        .HasConstraintName("FK__Student__faculty__3B75D760");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("FirstCrudExample.Models.Userlist", b =>
                {
                    b.HasOne("FirstCrudExample.Models.Usertype", "UserType")
                        .WithMany("Userlists")
                        .HasForeignKey("UserTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__USERLIST__userTy__59FA5E80");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("FirstCrudExample.Models.Faculty", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("FirstCrudExample.Models.Usertype", b =>
                {
                    b.Navigation("Userlists");
                });
#pragma warning restore 612, 618
        }
    }
}
